如果抛出了一个异常，try语句中的脚本将会停止执行，然后马上转向执行catch语句中的脚本。

如果异常抛出了却没有被捕捉到，就会产生一个`fatal error`

